### ISSUE TITLE
无法找到urouter模块！

### ISSUE THREAD

**Issue by gxk2000** [Li-Lian1069/micropython-urouter#5]
具体报错如下：
Traceback (most recent call last):
  File "main.py", line 3, in <module>
ImportError: no module named 'urouter'
MicroPython v1.18-601-g01f31ac23-dirty on 2022-03-29; ESP32 module with ESP32
Type "help()" for more information.

**Comment by gxk2000** [comment]
开发板具体文件目录如图：
https://s1.locimg.com/2023/01/06/e1f1cee3b2cb2.png

**Comment by majoson-chen** [comment]
lib之下应该还有一个名为urouter的文件夹用于存放这些文件

**Comment by gxk2000** [comment]
> lib之下应该还有一个名为urouter的文件夹用于存放这些文件

还是不行
[img]https://m.360buyimg.com/babel/jfs/t1/181540/2/31308/70623/63bac4a1F91cbc76c/917cf2a3e53c1070.png[/img]

**Comment by majoson-chen** [comment]
那你把lib文件夹删掉吧，直接把urouter文件夹放到根目录
